spring.application.name=covveeAuthService
spring.datasource.url=jdbc:postgresql://localhost:3307/covvee
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
