server:
  port: 8080

spring:
  application:
    name: Gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE    # <--- Matches the name in your Eureka image
              predicates:
                - Path=/auth/**

            - id: project-service
              uri: lb://PROJECT-SERVICE
              predicates:
                - Path=/project/**

            - id: file-service
              uri: lb://FILE-SERVICE
              predicates:
                - Path=/file/**

            - id: code-service
              uri: lb://CODE-SERVICE
              predicates:
                - Path=/code/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/