server:
  port: 8080

spring:
  application:
    name: covveeApiGateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        - id: project-service
          uri: http://localhost:8082
          predicates:
            - Path=/project/**
